services:
  users:
    restart: always
    env_file: 
      - .env
    environment:

      ENVIRONMENT: ${ENVIRONMENT}

      DATABASE_URI_LOCAL: ${DATABASE_URI_LOCAL}

      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}

      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      PASSWORD_EMAIL: ${PASSWORD_EMAIL}
      SECRET_KEY_EMAIL: ${SECRET_KEY_EMAIL}
      ALGORITHM_EMAIL: ${ALGORITHM_EMAIL}

      USERS_LOCALHOST: ${USERS_LOCALHOST}

    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8001:8080