services:

    users_db:
      image: postgres:alpine
      env_file:
        - .env
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_USERS}
        POSTGRES_USER: ${POSTGRES_USER_USERS}
        POSTGRES_DB: ${POSTGRES_DB_USERS}
      expose:
        - 5432
    
    users_ms:
      restart: always
      env_file: 
        - .env
      environment:
        DATABASE_URI_USERS: ${DATABASE_URI_USERS}
        USERS_LOCALHOST: ${USERS_LOCALHOST}
        SECRET_KEY: ${SECRET_KEY}
        ALGORITHM: ${ALGORITHM}
        ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}

      build: ../users
      command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
      ports:
        - 8001:8000
      depends_on:
        - users_db