"""test client_preference

Revision ID: aed39858018c
Revises: 05859cbc5c7f
Create Date: 2023-10-15 00:26:23.711301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aed39858018c'
down_revision: Union[str, None] = '05859cbc5c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_preference_id', table_name='client_preference')
    op.drop_table('client_preference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_preference',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='client_preference_client_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='client_preference_pkey')
    )
    op.create_index('ix_client_preference_id', 'client_preference', ['id'], unique=False)
    # ### end Alembic commands ###
