"""token is active to bool

Revision ID: f34079ea8658
Revises: fa09380b14fc
Create Date: 2023-10-17 22:27:53.097305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f34079ea8658'
down_revision: Union[str, None] = 'fa09380b14fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('token', 'is_active')

    # Agregar una nueva columna con el tipo BOOLEAN
    op.add_column('token', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'is_active',
               existing_type=sa.Boolean(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
